import SwiftUI

/// A view for adding a new word with auto-generated example sentences.
///
/// This view provides a form for entering word information (word, meaning, phonetic)
/// and a button to automatically generate example sentences using OpenAI API.
///
/// ## Features
/// - Input fields for word, meaning, and phonetic transcription
/// - Prompt preset picker (local selection, defaults to global active preset)
/// - Auto-generation of example sentences via OpenAI
/// - Preview of generated sentences with categories
/// - Save functionality to persist the word
struct AddWordView: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var settings: SettingsManager
    @StateObject private var openAIService = OpenAIService()

    /// The English word to add.
    @State private var word: String = ""

    /// The Japanese meaning of the word.
    @State private var meaning: String = ""

    /// The phonetic transcription of the word.
    @State private var phonetic: String = ""

    /// The sentences generated by OpenAI.
    @State private var generatedSentences: [Sentence] = []

    /// Whether to show the error alert.
    @State private var showingAlert = false

    /// The error message to display in the alert.
    @State private var alertMessage = ""

    /// The locally selected preset ID (not bound back to global settings).
    @State private var selectedPresetID: UUID = PromptPreset.general.id

    /// Whether the preset disclosure group is expanded.
    @State private var isPresetSectionExpanded: Bool = false

    /// Callback invoked when a word is successfully saved.
    var onSave: ((Word) -> Void)?

    var body: some View {
        NavigationStack {
            Form {
                Section(header: Text("単語情報")) {
                    TextField("英単語", text: $word)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()

                    TextField("意味", text: $meaning)

                    TextField("発音記号", text: $phonetic)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                }

                Section {
                    DisclosureGroup(isExpanded: $isPresetSectionExpanded) {
                        Picker("プリセット", selection: $selectedPresetID) {
                            ForEach(settings.allPresets) { preset in
                                Text(preset.name).tag(preset.id)
                            }
                        }
                        .pickerStyle(.menu)

                        let selectedPreset = settings.allPresets.first { $0.id == selectedPresetID }
                        if let conditions = selectedPreset?.conditions {
                            Text(conditions)
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    } label: {
                        HStack {
                            Image(systemName: "text.alignleft")
                                .foregroundColor(.accentColor)
                            VStack(alignment: .leading, spacing: 2) {
                                Text("例文生成の条件")
                                    .font(.body)
                                let activeName = settings.allPresets.first { $0.id == selectedPresetID }?.name
                                    ?? settings.activePreset.name
                                Text(activeName)
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                }

                Section {
                    Button(action: {
                        Task {
                            await generateSentences()
                        }
                    }) {
                        HStack {
                            if openAIService.isLoading {
                                ProgressView()
                                    .progressViewStyle(CircularProgressViewStyle())
                                Text("生成中...")
                            } else {
                                Image(systemName: "pencil.and.list.clipboard")
                                Text("例文を自動生成")
                            }
                        }
                        .frame(maxWidth: .infinity)
                        .frame(height: 44)
                    }
                    .disabled(word.isEmpty || meaning.isEmpty || openAIService.isLoading)
                }

                if !generatedSentences.isEmpty {
                    Section(header: Text("生成された例文 (\(generatedSentences.count)個)")) {
                        ForEach(generatedSentences) { sentence in
                            VStack(alignment: .leading, spacing: 4) {
                                Text(sentence.english)
                                    .font(.body)
                                Text(sentence.japanese)
                                    .font(.subheadline)
                                    .foregroundColor(.secondary)
                                if !sentence.category.isEmpty {
                                    Text(sentence.category)
                                        .font(.caption)
                                        .padding(.horizontal, 6)
                                        .padding(.vertical, 2)
                                        .background(Color.blue.opacity(0.1))
                                        .foregroundColor(.blue)
                                        .cornerRadius(4)
                                }
                            }
                            .padding(.vertical, 4)
                        }
                    }
                }

                if !generatedSentences.isEmpty {
                    Section {
                        Button(action: saveWord) {
                            HStack {
                                Image(systemName: "checkmark.circle.fill")
                                Text("保存")
                            }
                            .frame(maxWidth: .infinity)
                            .frame(height: 44)
                            .foregroundColor(.white)
                        }
                        .listRowBackground(Color.green)
                    }
                }
            }
            .navigationTitle("単語を追加")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    Button("キャンセル") {
                        dismiss()
                    }
                }
            }
            .onAppear {
                selectedPresetID = settings.activePresetID
            }
            .alert("エラー", isPresented: $showingAlert) {
                Button("OK", role: .cancel) {}
            } message: {
                Text(alertMessage)
            }
        }
    }

    // MARK: - Private Methods

    /// Generates example sentences using the OpenAI service.
    ///
    /// Uses the locally selected preset's conditions for generation.
    /// Updates `generatedSentences` on success or shows an alert on failure.
    private func generateSentences() async {
        let conditions = settings.allPresets.first { $0.id == selectedPresetID }?.conditions
            ?? settings.activeConditions
        do {
            let sentences = try await openAIService.generateSentences(for: word, meaning: meaning, conditions: conditions)
            await MainActor.run {
                generatedSentences = sentences
            }
        } catch {
            await MainActor.run {
                alertMessage = error.localizedDescription
                showingAlert = true
            }
        }
    }

    /// Creates a new word and passes it to the callback.
    ///
    /// Creates a new `Word` object with the entered information and generated sentences,
    /// then passes it to the `onSave` callback. Persistence is handled by the caller.
    private func saveWord() {
        let newWord = Word(
            word: word,
            meaning: meaning,
            phonetic: phonetic,
            sentences: generatedSentences
        )

        onSave?(newWord)
        dismiss()
    }
}

#Preview {
    AddWordView()
        .environmentObject(SettingsManager.shared)
}
