import SwiftUI

struct TermsOfServiceView: View {
    @State private var isJapanese = true

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {

                Picker("", selection: $isJapanese) {
                    Text("日本語").tag(true)
                    Text("English").tag(false)
                }
                .pickerStyle(.segmented)
                .padding(.bottom, 4)

                if isJapanese {
                    japaneseContent
                } else {
                    englishContent
                }
            }
            .padding(20)
        }
        .navigationTitle(isJapanese ? "利用規約" : "Terms of Service")
        .navigationBarTitleDisplayMode(.inline)
    }

    // MARK: - Japanese

    private var japaneseContent: some View {
        VStack(alignment: .leading, spacing: 24) {
            policyText("最終更新日：2026年2月")

            section("1. 同意") {
                policyText("WordCraft（以下「本アプリ」）をダウンロードまたは使用することにより、本利用規約に同意したものとみなします。同意しない場合は本アプリをご使用にならないでください。")
            }

            section("2. サービスの説明") {
                policyText("本アプリ（WordCraft）は英単語の登録・発音練習・AI例文生成を行う個人向け語学学習ツールです。AI機能はお客様自身のAPI認証情報を使用するサードパーティサービスを介して提供されます。")
            }

            section("3. ユーザーの責任") {
                bulletItem("APIキー", "OpenAI APIキーの取得・管理・セキュリティ確保はお客様の責任となります。APIキーの使用により発生した費用はお客様の負担となります。")
                bulletItem("登録コンテンツ", "本アプリに登録する単語・例文に関する責任はお客様が負います。")
                bulletItem("適切な使用", "違法な目的や他者への損害を与えるような方法での使用を禁止します。")
            }

            section("4. AI生成コンテンツの免責") {
                policyText("AIが生成する例文は学習目的のみで提供されます。開発者はAI生成コンテンツの正確性・適切性・完全性について一切の保証を行いません。重要な語学表現は権威ある情報源で確認してください。")
            }

            section("5. サードパーティサービス") {
                policyText("本アプリはOpenAIおよびAWSのサービスと連携します。これらのサービスの利用はそれぞれの利用規約に従います。開発者はOpenAIおよびAmazon Web Servicesとは無関係であり、公式に承認されたものではありません。")
            }

            section("6. 保証の否認") {
                policyText("本アプリは「現状のまま」「提供可能な状態で」提供され、商品性・特定目的への適合性・非侵害性を含む明示または黙示の保証を一切行いません。")
            }

            section("7. 責任の制限") {
                policyText("適用法令が許す最大限の範囲において、開発者は本アプリの使用または使用不能から生じる間接的・付随的・特別・結果的または懲罰的損害について一切の責任を負いません。")
            }

            section("8. 規約の変更") {
                policyText("本規約は随時更新される場合があります。変更後も引き続き本アプリを使用した場合、改訂された規約に同意したものとみなします。更新版はアプリ内でご確認いただけます。")
            }

            section("9. お問い合わせ") {
                policyText("本規約に関するご質問は以下からお問い合わせください：\nhttps://github.com/KazusaNakagawa/english_learn_app/issues")
            }
        }
    }

    // MARK: - English

    private var englishContent: some View {
        VStack(alignment: .leading, spacing: 24) {
            policyText("Last updated: February 2026")

            section("1. Acceptance of Terms") {
                policyText("By downloading or using WordCraft (hereinafter \"the App\"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.")
            }

            section("2. Description of Service") {
                policyText("WordCraft is a personal vocabulary learning tool that allows you to register English words, practice pronunciation, and generate example sentences using third-party AI services via your own API credentials.")
            }

            section("3. User Responsibilities") {
                bulletItem("API Keys", "You are solely responsible for obtaining, managing, and securing your own OpenAI API key. Any costs incurred through your API key usage are your responsibility.")
                bulletItem("Content", "You are responsible for the words and sentences you register in the App.")
                bulletItem("Acceptable Use", "You agree not to use the App for any unlawful purpose or in any way that could harm others.")
            }

            section("4. AI-Generated Content Disclaimer") {
                policyText("Example sentences generated by the AI are provided for educational purposes only. The developer makes no warranty regarding the accuracy, appropriateness, or completeness of AI-generated content. Always verify important language usage with authoritative sources.")
            }

            section("5. Third-Party Services") {
                policyText("The App integrates with OpenAI and AWS services. Your use of those services is governed by their respective Terms of Service. The developer is not affiliated with or endorsed by OpenAI or Amazon Web Services.")
            }

            section("6. Disclaimer of Warranties") {
                policyText("The App is provided \"as is\" and \"as available\" without warranty of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.")
            }

            section("7. Limitation of Liability") {
                policyText("To the maximum extent permitted by applicable law, the developer shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the App.")
            }

            section("8. Changes to Terms") {
                policyText("These Terms may be updated from time to time. Continued use of the App after changes constitutes acceptance of the revised terms. The updated version will be available within the App.")
            }

            section("9. Contact") {
                policyText("For questions regarding these Terms, please open an issue at:\nhttps://github.com/KazusaNakagawa/english_learn_app/issues")
            }
        }
    }

    // MARK: - Helpers

    private func section(_ title: String, @ViewBuilder content: () -> some View) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
            content()
        }
    }

    private func bulletItem(_ heading: String, _ body: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text("• \(heading)")
                .font(.subheadline).bold()
            Text(body)
                .font(.subheadline)
                .foregroundColor(.secondary)
        }
    }

    private func policyText(_ text: String) -> some View {
        Text(text)
            .font(.subheadline)
            .foregroundColor(.secondary)
            .fixedSize(horizontal: false, vertical: true)
    }
}

#Preview {
    NavigationStack {
        TermsOfServiceView()
    }
}
