import SwiftUI

struct TermsOfServiceView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {

                Group {
                    policyText("Last updated: February 2026")
                        .foregroundColor(.secondary)

                    section("1. Acceptance of Terms") {
                        policyText(
                            "By downloading or using EnglishLearnApp (\"the App\"), you agree to be bound by these Terms of Service. " +
                            "If you do not agree, please do not use the App."
                        )
                    }

                    section("2. Description of Service") {
                        policyText(
                            "The App is a personal vocabulary learning tool that allows you to register English words, " +
                            "practice pronunciation, and generate example sentences using third-party AI services " +
                            "via your own API credentials."
                        )
                    }

                    section("3. User Responsibilities") {
                        bulletItem("API Keys", "You are solely responsible for obtaining, managing, and securing your own OpenAI API key. Any costs incurred through your API key usage are your responsibility.")
                        bulletItem("Content", "You are responsible for the words and sentences you register in the App.")
                        bulletItem("Acceptable Use", "You agree not to use the App for any unlawful purpose or in any way that could harm others.")
                    }

                    section("4. AI-Generated Content Disclaimer") {
                        policyText(
                            "Example sentences generated by the AI (OpenAI) are provided for educational purposes only. " +
                            "The developer makes no warranty regarding the accuracy, appropriateness, or completeness of AI-generated content. " +
                            "Always verify important language usage with authoritative sources."
                        )
                    }

                    section("5. Third-Party Services") {
                        policyText(
                            "The App integrates with OpenAI and AWS services. Your use of those services is governed by their respective Terms of Service. " +
                            "The developer is not affiliated with or endorsed by OpenAI or Amazon Web Services."
                        )
                    }
                }

                Group {
                    section("6. Disclaimer of Warranties") {
                        policyText(
                            "The App is provided \"as is\" and \"as available\" without warranty of any kind, " +
                            "either express or implied, including but not limited to warranties of merchantability, " +
                            "fitness for a particular purpose, or non-infringement."
                        )
                    }

                    section("7. Limitation of Liability") {
                        policyText(
                            "To the maximum extent permitted by applicable law, the developer shall not be liable " +
                            "for any indirect, incidental, special, consequential, or punitive damages arising from " +
                            "your use of or inability to use the App."
                        )
                    }

                    section("8. Changes to Terms") {
                        policyText(
                            "These Terms of Service may be updated from time to time. " +
                            "Continued use of the App after changes constitutes acceptance of the revised terms. " +
                            "The updated version will be available within the App."
                        )
                    }

                    section("9. Contact") {
                        policyText(
                            "For questions regarding these Terms, please open an issue at:\n" +
                            "https://github.com/KazusaNakagawa/english_learn_app/issues"
                        )
                    }
                }
            }
            .padding(20)
        }
        .navigationTitle("Terms of Service")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func section(_ title: String, @ViewBuilder content: () -> some View) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
            content()
        }
    }

    private func bulletItem(_ heading: String, _ body: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text("• \(heading)")
                .font(.subheadline).bold()
            Text(body)
                .font(.subheadline)
                .foregroundColor(.secondary)
        }
    }

    private func policyText(_ text: String) -> some View {
        Text(text)
            .font(.subheadline)
            .foregroundColor(.secondary)
            .fixedSize(horizontal: false, vertical: true)
    }
}

#Preview {
    NavigationStack {
        TermsOfServiceView()
    }
}
