#!/usr/bin/env node
/**
 * Reads web/poc/.env and writes web/poc/env.js
 * Run: node generate-env.js
 */
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.error('ERROR: .env not found. Copy .env.example to .env and fill in the values.');
  process.exit(1);
}

const lines = fs.readFileSync(envPath, 'utf8').split('\n');
const env = {};
for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eqIdx = trimmed.indexOf('=');
  if (eqIdx === -1) continue;
  const key = trimmed.slice(0, eqIdx).trim();
  const val = trimmed.slice(eqIdx + 1).trim();
  env[key] = val;
}

const required = ['VOICEVOX_ENDPOINT_POC', 'VOICEVOX_API_KEY_POC'];
const missing = required.filter(k => !env[k]);
if (missing.length) {
  console.error(`ERROR: Missing required keys in .env: ${missing.join(', ')}`);
  process.exit(1);
}

const output = `// Auto-generated by generate-env.js — DO NOT COMMIT
window.VOICEVOX_ENDPOINT_POC = "${env.VOICEVOX_ENDPOINT_POC}";
window.VOICEVOX_API_KEY_POC  = "${env.VOICEVOX_API_KEY_POC}";
`;

fs.writeFileSync(path.join(__dirname, 'env.js'), output);
console.log('env.js generated successfully.');
